import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  applyTokenOverrides,
  compileCss,
  compileCssWithStyleDictionary,
  createStyleDictionarySnapshot,
  flattenTokens,
  mergeDocuments,
  resolveDocument,
  resolveModePlan,
} from '../dist/src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

async function readJson(relativePath) {
  return JSON.parse(await readFile(resolve(root, relativePath), 'utf8'));
}

async function loadFoundation() {
  const profile = await readJson('config/pfx-foundations.v0.1.json');
  const paths = Object.values(profile.families).flatMap((family) => [family.primitive, family.semantic]);
  const documents = await Promise.all(paths.map(readJson));
  return mergeDocuments(...documents);
}

function variableNames(css) {
  return new Set([...css.matchAll(/(--pfx-[a-z0-9-]+):/g)].map((match) => match[1]));
}

test('Style Dictionary adapter compiles the complete PFx foundation', async () => {
  const foundation = await loadFoundation();
  const css = await compileCssWithStyleDictionary(foundation);

  assert.match(css, /^\/\* Generated by PFx Interface Core via Style Dictionary\./);
  assert.match(css, /--pfx-color-text-primary:/);
  assert.match(css, /--pfx-space-control-inline-md:/);
  assert.match(css, /--pfx-shadow-overlay-default:/);
  assert.match(css, /--pfx-size-target-minimum:\s*24px;/);
  assert.match(css, /--pfx-z-layer-modal:\s*1100;/);
});

test('vendor adapter and reference compiler expose the same PFx custom-property surface', async () => {
  const foundation = await loadFoundation();
  const reference = compileCss(foundation);
  const vendor = await compileCssWithStyleDictionary(foundation);
  assert.deepEqual(variableNames(vendor), variableNames(reference));
});

test('Style Dictionary adapter handles a fully composed mode selection', async () => {
  const [foundation, profile] = await Promise.all([
    loadFoundation(),
    readJson('config/pfx-modes.v0.1.json'),
  ]);
  const plan = resolveModePlan(profile, {
    colorScheme: 'dark',
    contrast: 'high',
    density: 'compact',
    motion: 'reduced',
  });
  const overrides = await Promise.all(plan.files.map(readJson));
  const composed = applyTokenOverrides(foundation, ...overrides);
  const css = await compileCssWithStyleDictionary(composed);

  assert.match(css, /--pfx-space-control-inline-md:\s*12px;/);
  assert.match(css, /--pfx-motion-duration-default:\s*120ms;/);
  assert.match(css, /--pfx-color-border-default:/);
});

test('Style Dictionary adapter honors PFx selector and header options', async () => {
  const foundation = await loadFoundation();
  const css = await compileCssWithStyleDictionary(foundation, {
    selector: '[data-pfx-theme="preview"]',
    header: '/* PFx test */',
  });
  assert.match(css, /^\/\* PFx test \*\//);
  assert.match(css, /\[data-pfx-theme="preview"\]\s*\{/);
});

test('resolved vendor snapshot contains no PFx token aliases', async () => {
  const foundation = await loadFoundation();
  const snapshot = createStyleDictionarySnapshot(resolveDocument(foundation).tokens);
  for (const token of flattenTokens(snapshot)) {
    assert.equal(
      typeof token.value === 'string' && /^\{[^{}]+\}$/.test(token.value),
      false,
      token.name,
    );
  }
});

test('DTCG $root keeps the PFx root-token variable name through Style Dictionary', async () => {
  const document = {
    color: {
      accent: {
        $type: 'color',
        $root: {
          $value: {
            colorSpace: 'srgb',
            components: [1, 0, 0],
          },
        },
      },
    },
  };

  const css = await compileCssWithStyleDictionary(document);
  assert.match(css, /--pfx-color-accent:/);
  assert.equal(css.includes('--pfx-color-accent-root:'), false);
});
