import type { ColorValue, DimensionValue, TokenDocument } from '../core/index.js';
import { isRecord } from '../core/index.js';
import { resolveDocument, type ResolvedToken } from '../resolver/index.js';

export interface CssCompileOptions {
  selector?: string;
  header?: string;
}

export interface CompilerProvider {
  readonly name: string;
  compileCss(document: TokenDocument, options?: CssCompileOptions): string;
}

function customPropertyName(token: ResolvedToken): string {
  return `--pfx-${token.path.join('-')}`;
}

function serializeColor(value: unknown): string {
  if (!isRecord(value)) throw new Error('Color token must resolve to a structured color value.');
  const candidate = value as unknown as ColorValue;
  if (!Array.isArray(candidate.components) || typeof candidate.colorSpace !== 'string') {
    throw new Error('Invalid structured color value.');
  }

  const alpha = candidate.alpha ?? 1;
  const [a, b, c] = candidate.components;
  if (candidate.colorSpace.toLowerCase() === 'oklch') {
    if (typeof a !== 'number' || typeof b !== 'number' || (typeof c !== 'number' && c !== 'none')) {
      throw new Error('Invalid OKLCH components.');
    }
    const lightness = `${trimNumber(a * 100)}%`;
    const hue = c === 'none' ? 'none' : trimNumber(c);
    return `oklch(${lightness} ${trimNumber(b)} ${hue}${alpha < 1 ? ` / ${trimNumber(alpha)}` : ''})`;
  }

  const serializedComponents = candidate.components.map((item) => String(item)).join(' ');
  return `color(${candidate.colorSpace} ${serializedComponents}${alpha < 1 ? ` / ${trimNumber(alpha)}` : ''})`;
}

function serializeDimension(value: unknown): string {
  if (!isRecord(value)) throw new Error('Dimension token must resolve to a structured dimension value.');
  const candidate = value as unknown as DimensionValue;
  if (typeof candidate.value !== 'number' || typeof candidate.unit !== 'string') {
    throw new Error('Invalid dimension value.');
  }
  return `${trimNumber(candidate.value)}${candidate.unit}`;
}

function trimNumber(value: number): string {
  return Number(value.toFixed(6)).toString();
}

function serializeToken(token: ResolvedToken): string {
  switch (token.type) {
    case 'color':
      return serializeColor(token.resolvedValue);
    case 'dimension':
      return serializeDimension(token.resolvedValue);
    case 'number':
      return String(token.resolvedValue);
    case 'boolean':
      return token.resolvedValue ? 'true' : 'false';
    default:
      if (typeof token.resolvedValue === 'string' || typeof token.resolvedValue === 'number') {
        return String(token.resolvedValue);
      }
      throw new Error(`Reference compiler does not yet serialize token type: ${token.type ?? 'unknown'}`);
  }
}

export const referenceCompiler: CompilerProvider = {
  name: 'pfx-reference',
  compileCss(document, options = {}) {
    const selector = options.selector ?? ':root';
    const header = options.header ?? '/* Generated by PFx Interface Core. Do not edit directly. */';
    const resolved = resolveDocument(document).tokens;
    const lines = resolved
      .slice()
      .sort((left, right) => left.name.localeCompare(right.name))
      .map((token) => `  ${customPropertyName(token)}: ${serializeToken(token)};`);

    return `${header}\n${selector} {\n${lines.join('\n')}\n}\n`;
  },
};

export function compileCss(document: TokenDocument, options?: CssCompileOptions): string {
  return referenceCompiler.compileCss(document, options);
}
