import StyleDictionary from 'style-dictionary';
import { formats, transformGroups } from 'style-dictionary/enums';

import {
  isRecord,
  type TokenDocument,
  type TokenType,
  type TokenValue,
} from '../core/index.js';
import { resolveDocument, type ResolvedToken } from '../resolver/index.js';
import { validateDocument } from '../validator/index.js';

interface StyleDictionaryCssOptions {
  selector?: string;
  header?: string;
}

function cloneValue<T>(value: T): T {
  if (Array.isArray(value)) return value.map((item) => cloneValue(item)) as unknown as T;
  if (isRecord(value)) {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, cloneValue(item)]),
    ) as unknown as T;
  }
  return value;
}

function writeResolvedToken(
  document: TokenDocument,
  path: readonly string[],
  type: TokenType,
  value: TokenValue,
): void {
  if (path.length === 0) throw new Error('Cannot export a token with an empty path.');

  let node: Record<string, unknown> = document;
  for (const segment of path.slice(0, -1)) {
    const current = node[segment];
    if (current === undefined) {
      const next: Record<string, unknown> = {};
      node[segment] = next;
      node = next;
      continue;
    }
    if (!isRecord(current)) {
      throw new Error(`Cannot export token path through a non-object node: ${path.join('.')}`);
    }
    node = current;
  }

  const leaf = path.at(-1);
  if (!leaf) throw new Error('Cannot export a token with an empty path.');
  if (node[leaf] !== undefined) throw new Error(`Duplicate vendor token path: ${path.join('.')}`);

  node[leaf] = {
    $type: type,
    $value: cloneValue(value),
  };
}

export function createStyleDictionarySnapshot(tokens: readonly ResolvedToken[]): TokenDocument {
  const snapshot: TokenDocument = {};
  for (const token of tokens) {
    writeResolvedToken(snapshot, token.path, token.type, token.resolvedValue);
  }
  return snapshot;
}

function assertValidSource(document: TokenDocument): void {
  const validation = validateDocument(document);
  if (validation.valid) return;
  const details = validation.issues
    .map((issue) => `${issue.path}: ${issue.message}`)
    .join('\n');
  throw new Error(`Token validation failed:\n${details}`);
}

export async function compileCssWithStyleDictionary(
  document: TokenDocument,
  options: StyleDictionaryCssOptions = {},
): Promise<string> {
  assertValidSource(document);

  const resolved = resolveDocument(document);
  const snapshot = createStyleDictionarySnapshot(resolved.tokens);
  const selector = options.selector ?? ':root';
  const header = options.header ?? '/* Generated by PFx Interface Core via Style Dictionary. Do not edit directly. */';

  const styleDictionary = new StyleDictionary({
    tokens: snapshot,
    usesDtcg: true,
    platforms: {
      css: {
        transformGroup: transformGroups.css,
        prefix: 'pfx',
        files: [
          {
            format: formats.cssVariables,
            options: {
              showFileHeader: false,
              outputReferences: false,
              selector,
              sort: 'name',
            },
          },
        ],
      },
    },
  });

  const outputs = await styleDictionary.formatPlatform('css');
  const output = outputs[0]?.output;
  if (typeof output !== 'string') {
    throw new Error('Style Dictionary did not produce a CSS string.');
  }

  return `${header}\n${output.trimStart()}`;
}

export const styleDictionaryCompiler = {
  name: 'style-dictionary',
  compileCss: compileCssWithStyleDictionary,
} as const;
